feelings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from thoughts import urls as thought_urls
from users import urls as user_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
]

thoughts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.CreateThought.as_view(), name='create'),
]

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^', include('django.contrib.auth.urls')),
]

thoughts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

CONDITIONS = (
    (0, 'Ecstatic'),
    (5, 'Passionate'),
    (10, 'Happy'),
    (16, 'Optimistic'),
    (20, 'Content'),
    (25, 'Bored'),
    (26, 'Tired'),
    (27, 'Hungry'),
    (30, 'Pessimistic'),
    (35, 'Frustrated'),
    (40, 'Overwhelmed'),
    (45, 'Disappointed'),
    (50, 'Worried'),
    (55, 'Angry'),
    (60, 'Jealous'),
    (65, 'Insecure'),
    (70, 'Guilty'),
    (75, 'Fear'),
    (80, 'Grief'),
    (85, 'Despair'),
    (90, 'Paranoid'),
)

class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts')
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    condition = models.IntegerField(choices=CONDITIONS)
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: {}'.format(self.recorded_at.strftime('%Y-%m-%d %H:%M:%S'), self.get_condition_display())

users/models.py
from django.db import models

# Create your models here.

thoughts/forms.py
from django import forms

from . import models

class ThoughtForm(forms.ModelForm):
    class Meta:
        fields = {'condition', 'notes'}
        model = models.Thought

users/forms.py
from django import forms

class LogoutForm(forms.Form):
    pass

thoughts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

from .forms import ThoughtForm


class CreateThought(LoginRequiredMixin, CreateView):
    form_class = ThoughtForm
    success_url = reverse_lazy('users:dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.views import generic

from . import forms

class Dashboard(LoginRequiredMixin, generic.TemplateView):
    template_name = 'users/dashboard.html'

def dashboard(request):
    return render(request, 'users/dashboard.html')

class LogoutView(LoginRequiredMixin, generic.FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

templates/index.html
{% extends "layout.html" %}

{% block content %}
<h1>Welcome to feelings!</h1>
        <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Feelings</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div> <!-- /container -->
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Feelings{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/feelings.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Feelings</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
              <li><a href="{% url 'users:login' %}">Login</a></li>
              <li><a href="{% url 'users:signup' %}">Sign Up</a></li>
          {% else %}
              <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
          {% endif %}
          </ul>
      </div><!--/.navbar-collapse -->
    </nav>

    <div id="content">

    {% block content %}
    {% endblock %}

    </div>

    <div class="container">
      <hr>
      <footer>
        <p>&copy; Company 2017</p>
      </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

thoughts/templates/thoughts/_form.html
{% load bootstrap3 %}

<form method="POST" action="{% url 'thoughts:create' %}">
    <h2>How're you feeling?</h2>
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">{% bootstrap_field form.condition layout='horizontal' %}</div>
        <div class="col-md-6">{% bootstrap_field form.notes layout='horizontal' %}</div>
        <div class="col-md-2">{% buttons submit='Record' %}{% endbuttons %}</div>
    </div>
</form>

users/templates/users/dashboard.html
{% extends "layout.html" %}

{% load thought_tags %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    {% thought_form %}
    <h1>Dashboard</h1>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "layout.html" %}

{% block title %}Logout | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>You sure?</h3>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Come back soon!</h3>
            <p>This site works best if you use it often!</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title  %}Sign Up | {% endblock %}

{% block content %}
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>Login</h3>
            <form action="" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <input type="submit" value="Sign Up" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-6">
            <h2>Record how you're feeling!</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad architecto asperiores dolorem eius eum, eveniet ex explicabo fugiat ipsam molestiae molestias, mollitia nesciunt nobis officia possimus rerum sequi temporibus, voluptatem.</p>

        </div>
    </div>
</div>
{% endblock %}